import type { ImGuiMenu, ImGuiElement } from '@/types/imgui';

function generateElement(el: ImGuiElement, indent = '    '): string {
  const lines: string[] = [];
  switch (el.type) {
    case 'text':
      lines.push(`${indent}ImGui::Text("${el.label}");`);
      break;
    case 'button':
      lines.push(`${indent}if (ImGui::Button("${el.label}")) {`);
      lines.push(`${indent}    // TODO: handle button click`);
      lines.push(`${indent}}`);
      break;
    case 'checkbox': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      lines.push(`${indent}ImGui::Checkbox("${el.label}", &b_${varName});`);
      break;
    }
    case 'slider': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      const min = (el.props.min as number) ?? 0;
      const max = (el.props.max as number) ?? 100;
      lines.push(`${indent}ImGui::SliderFloat("${el.label}", &f_${varName}, ${min}.0f, ${max}.0f);`);
      break;
    }
    case 'input': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      lines.push(`${indent}ImGui::InputText("${el.label}", buf_${varName}, sizeof(buf_${varName}));`);
      break;
    }
    case 'combo': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      const items = (el.props.items as string[]) ?? ['Item 1', 'Item 2'];
      lines.push(`${indent}const char* items_${varName}[] = { ${items.map(i => `"${i}"`).join(', ')} };`);
      lines.push(`${indent}ImGui::Combo("${el.label}", &i_${varName}, items_${varName}, IM_ARRAYSIZE(items_${varName}));`);
      break;
    }
    case 'separator':
      lines.push(`${indent}ImGui::Separator();`);
      break;
    case 'collapser':
      lines.push(`${indent}if (ImGui::CollapsingHeader("${el.label}")) {`);
      lines.push(`${indent}    // TODO: content`);
      lines.push(`${indent}}`);
      break;
    case 'treenode':
      lines.push(`${indent}if (ImGui::TreeNode("${el.label}")) {`);
      lines.push(`${indent}    // TODO: content`);
      lines.push(`${indent}    ImGui::TreePop();`);
      lines.push(`${indent}}`);
      break;
    case 'colorpicker': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      lines.push(`${indent}ImGui::ColorEdit4("${el.label}", color_${varName});`);
      break;
    }
    case 'progressbar': {
      const val = (el.props.value as number) ?? 0.5;
      lines.push(`${indent}ImGui::ProgressBar(${val}f, ImVec2(-FLT_MIN, 0), "${el.label}");`);
      break;
    }
    case 'listbox': {
      const varName = el.label.toLowerCase().replace(/\s+/g, '_');
      lines.push(`${indent}ImGui::ListBox("${el.label}", &i_${varName}, items_${varName}, IM_ARRAYSIZE(items_${varName}), 4);`);
      break;
    }
    default:
      lines.push(`${indent}// Unknown element: ${el.type}`);
  }
  return lines.join('\n');
}

export function generateCode(menu: ImGuiMenu): string {
  const lines: string[] = [];
  lines.push(`// Generated by ImGui Builder`);
  lines.push(`// Menu: ${menu.name}`);
  lines.push(`#include "imgui.h"`);
  lines.push(``);
  lines.push(`void Render${menu.name.replace(/\s+/g, '')}() {`);
  lines.push(`    ImGui::SetNextWindowSize(ImVec2(${menu.width}, ${menu.height}), ImGuiCond_FirstUseEver);`);
  lines.push(`    ImGui::Begin("${menu.name}");`);
  lines.push(``);

  if (menu.tabs.length > 1) {
    lines.push(`    if (ImGui::BeginTabBar("##tabs")) {`);
    for (const tab of menu.tabs) {
      lines.push(`        if (ImGui::BeginTabItem("${tab.name}")) {`);
      for (const el of tab.elements) {
        lines.push(generateElement(el, '            '));
      }
      lines.push(`            ImGui::EndTabItem();`);
      lines.push(`        }`);
    }
    lines.push(`        ImGui::EndTabBar();`);
    lines.push(`    }`);
  } else if (menu.tabs.length === 1) {
    for (const el of menu.tabs[0].elements) {
      lines.push(generateElement(el));
    }
  }

  lines.push(``);
  lines.push(`    ImGui::End();`);
  lines.push(`}`);

  return lines.join('\n');
}
